<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Indeks Rupiah_indeks-rupiah</name>
   <tag></tag>
   <elementGuidId>d41463d3-8b1b-4ca8-aa9c-39e3e2af96ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='indeks-rupiah']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#indeks-rupiah</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15104a11-ba9a-4e69-88ba-7564f3185ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2493bb6-d013-4c7a-a1f5-7032554f96b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uang</value>
      <webElementGuid>3fa2a801-b65b-4e95-97bc-23525fe98173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>indeks-rupiah</value>
      <webElementGuid>c49bcd27-778d-4d27-ba66-750fe6060b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>indeks-rupiah</value>
      <webElementGuid>d6b9ca2f-57f6-4ff3-855e-b3cf2e03bb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1200</value>
      <webElementGuid>d645242d-f3c9-4083-9d48-2fe02abf9c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;indeks-rupiah&quot;)</value>
      <webElementGuid>8e13ec10-ae56-4175-8821-31a127031a16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='indeks-rupiah']</value>
      <webElementGuid>5ac247d6-ed02-4b56-9044-7c98b0624d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[3]/div/div/div/form/div[4]/div/input</value>
      <webElementGuid>b1956f91-7b20-4e18-8661-59c20d0b4aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>d0d90562-c8e9-425e-bc80-8c85bfa41811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'indeks-rupiah' and @name = 'indeks-rupiah']</value>
      <webElementGuid>ff221ec1-aafc-45e0-a14c-f646c3b68fd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
