<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Bruto TPB Baru_bruto-tpb-baru</name>
   <tag></tag>
   <elementGuidId>fffd950b-5d79-4b0e-9407-7367a2909ab4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bruto-tpb-baru']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bruto-tpb-baru</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f32a4079-3ff3-4eed-b5a1-bf83bd217332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cc524fb6-28a6-4195-9121-c081d3970292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uang</value>
      <webElementGuid>75cd1b32-e006-449b-b28e-e1e6efb7c2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bruto-tpb-baru</value>
      <webElementGuid>185e41f5-6904-414b-8996-562dafa9d7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bruto-tpb-baru</value>
      <webElementGuid>7261d5d3-357f-47b8-85b8-95a587ae0fe8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4968000</value>
      <webElementGuid>f56d9cea-a81c-4e95-9dc8-ac617c6b7cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bruto-tpb-baru&quot;)</value>
      <webElementGuid>d6960d9b-a578-40d6-a6b2-86aa8efaad0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bruto-tpb-baru']</value>
      <webElementGuid>d06df6f9-b048-4d7c-bee3-5a410bb6a255</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[3]/div/div/div/form/div[11]/div/input</value>
      <webElementGuid>a1655169-8301-4c2f-9ab0-a95773ee0e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>85f6bcfa-9cf3-4a91-9967-90946a766732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'bruto-tpb-baru' and @name = 'bruto-tpb-baru']</value>
      <webElementGuid>a0ab62f4-6777-4a90-b12e-ff2722b82afc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
