<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pemotong Tunjangan_pemotong-tunjangan</name>
   <tag></tag>
   <elementGuidId>acede7a4-b1bd-4e21-991a-ca3bc2a6ea3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pemotong-tunjangan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pemotong-tunjangan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>08d30eb3-dd53-4263-a4b9-a14a94ef2349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a77e1760-b7b6-4c1e-933e-4aa7e361fdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uang-positif</value>
      <webElementGuid>6b3ab272-e82d-4ff9-a4a0-1cdba7b47a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pemotong-tunjangan</value>
      <webElementGuid>a2d2fd87-3849-456d-98c6-0286aa71b3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pemotong-tunjangan</value>
      <webElementGuid>905f1372-a3f7-4ec6-827d-a624d2e25396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cc48288f-bf66-4245-be9b-f98036032fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pemotong-tunjangan&quot;)</value>
      <webElementGuid>319374c6-1a46-4ee6-b503-117e5e80cf18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pemotong-tunjangan']</value>
      <webElementGuid>d17e0e86-b1c9-4ebb-9f26-7fa64274312f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[3]/div/div/div/form/div[7]/div/input</value>
      <webElementGuid>e9621000-ee44-4663-86b7-330a8c8457ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/input</value>
      <webElementGuid>b8360dde-e063-440c-ad86-21d383639c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'pemotong-tunjangan' and @name = 'pemotong-tunjangan']</value>
      <webElementGuid>8dbebe7b-7c8d-4baa-a812-6b97ba3ff7ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
