<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Penambah Tunjangan_penambah-tunjangan</name>
   <tag></tag>
   <elementGuidId>5b258e94-8a77-463e-8b61-e4c67f6617a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='penambah-tunjangan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#penambah-tunjangan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f332eb8f-2b59-47e7-ad71-955de761f36d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ccdfbf5-4d2e-4075-8a60-5a84fc4cd2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uang-positif</value>
      <webElementGuid>09641c84-40df-4780-bccf-c2c8d2809c68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>penambah-tunjangan</value>
      <webElementGuid>10ede908-7a5e-4562-ab35-e896ad2c5886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>penambah-tunjangan</value>
      <webElementGuid>2321bd74-da40-4268-85e8-3ae6dc1848c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a4dfc63d-a7eb-4c09-86ef-46cf0d521b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;penambah-tunjangan&quot;)</value>
      <webElementGuid>0f64f58d-8e90-4c1c-a05d-7b6cd2288bfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='penambah-tunjangan']</value>
      <webElementGuid>03f5ff02-bfe6-4e37-bdec-fba798ec038a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[3]/div/div/div/form/div[9]/div/input</value>
      <webElementGuid>bc40401f-3dfa-43c7-b10a-2753bede4fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>6b7d4843-7840-472d-929b-3a1a949412bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'penambah-tunjangan' and @name = 'penambah-tunjangan']</value>
      <webElementGuid>8b8bc70b-02d4-4eba-8ea7-7de01dd413f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
