<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Belum Tervalidasi_id_tpb_validasi</name>
   <tag></tag>
   <elementGuidId>aba54b97-5dde-4db3-96b1-bb1729f28e0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='id_tpb_validasi[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;id_tpb_validasi[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71e6dad5-8f6c-4a50-bf44-30aebc696652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c7625ce3-0013-4424-8a9f-62e1c1069559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox-validasi</value>
      <webElementGuid>e23b5738-5c9d-419f-88f3-fa5460bceb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>id_tpb_validasi[]</value>
      <webElementGuid>b9d64d77-f02e-4316-b193-219c56be661b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>C6602898-6D97-48F5-AA2A-537121A0F403</value>
      <webElementGuid>d5640e9e-83ae-4fd6-9580-f4f8f0da8cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-penerimaan-tpb-0&quot;)/tbody[1]/tr[1]/td[@class=&quot;td-its text-center small&quot;]/input[@class=&quot;checkbox-validasi&quot;]</value>
      <webElementGuid>be3b8833-7b6a-4b4a-9628-f04cb531bb17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='id_tpb_validasi[]']</value>
      <webElementGuid>2ab92f52-6f58-45fc-9c73-ca2dfe27d77a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-penerimaan-tpb-0']/tbody/tr/td[19]/input</value>
      <webElementGuid>fb91a858-a87b-4674-8545-7d1f55c3095e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[19]/input</value>
      <webElementGuid>7199d16f-8dcd-4897-90de-6cd9721b24b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'id_tpb_validasi[]']</value>
      <webElementGuid>32b3bfcc-8013-4247-a3aa-43578a694e46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
