<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilih_bulan</name>
   <tag></tag>
   <elementGuidId>1f4d8748-8584-445c-8c28-9a8829bee2c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='bulan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bulan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>980b3c91-5e08-4452-8395-1fd2ef9b9f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bulan</value>
      <webElementGuid>bb30fa7e-a74b-4748-802b-e3e41a9ac9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bulan</value>
      <webElementGuid>e03f3307-8322-4e44-893a-9ae128d88227</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mr-2</value>
      <webElementGuid>188668c2-8b53-4646-980d-c3fe7d9f9088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Januari
                                                                        Februari
                                                                        Maret
                                                                        April
                                                                        Mei
                                                                        Juni
                                                                        Juli
                                                                        Agustus
                                                                        September
                                                                        Oktober
                                                                        November
                                                                        Desember
                                                                    </value>
      <webElementGuid>891f2448-97b2-421b-8eaf-6bbef59bece7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bulan&quot;)</value>
      <webElementGuid>883cde44-bf0e-4ef8-905a-e0fafdd8d62b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='bulan']</value>
      <webElementGuid>33d61b71-c4ae-49a3-bc8b-4a354dcdbee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div/div/div/div/form/div/div/div/select</value>
      <webElementGuid>ae05f819-5409-4761-be6c-63af8941e259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rilis Bruto TPB'])[2]/following::select[1]</value>
      <webElementGuid>fe0fb401-a880-42b9-ade9-7e6810a2d604</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan'])[1]/preceding::select[4]</value>
      <webElementGuid>b18c17ac-f5b7-4ea8-9203-b48413f90d51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6f768b47-8c58-4b4a-9206-5d8a104e06b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'bulan' and @id = 'bulan' and (text() = '
                                                                        Januari
                                                                        Februari
                                                                        Maret
                                                                        April
                                                                        Mei
                                                                        Juni
                                                                        Juli
                                                                        Agustus
                                                                        September
                                                                        Oktober
                                                                        November
                                                                        Desember
                                                                    ' or . = '
                                                                        Januari
                                                                        Februari
                                                                        Maret
                                                                        April
                                                                        Mei
                                                                        Juni
                                                                        Juli
                                                                        Agustus
                                                                        September
                                                                        Oktober
                                                                        November
                                                                        Desember
                                                                    ')]</value>
      <webElementGuid>6ebf2f38-f0b0-4d0f-b6f0-ec6b35fd2a9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
