<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Keterangan_keterangan</name>
   <tag></tag>
   <elementGuidId>8dd61e49-ef40-4153-994d-454737024d4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='keterangan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#keterangan</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>528890a4-e8c6-45c1-b22c-3df813b9a9d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b49341ad-96d2-4a29-bdc9-bfca79fa9d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>b655f1ef-71a6-42e3-b84a-7ebebbf8ee5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>keterangan</value>
      <webElementGuid>c7bf318a-2440-4ca7-b0ba-ee4608c173e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;keterangan&quot;)</value>
      <webElementGuid>c36f0267-0add-470a-ae1f-7b750f1e1725</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='keterangan']</value>
      <webElementGuid>2288b3ab-60ab-41a0-babf-feccd24c22ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div[3]/div/div/div/form/div[12]/div/textarea</value>
      <webElementGuid>6319ecb7-bcbf-4549-b65e-07583ed4692d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>290ea0d3-7d8e-4f57-98ab-55632d3d4aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'keterangan' and @name = 'keterangan']</value>
      <webElementGuid>bbb100ec-d0f4-4164-a4de-87a6dbc847e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
