<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Dosen_btn btn-danger btn-icon</name>
   <tag></tag>
   <elementGuidId>129b2aaa-c9f8-4eb0-a7e0-ed0901bb7eef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-danger.btn-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f0cf99c-36f8-4a1c-8f40-36d65ca331a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>84934e09-e863-4f54-87de-ae9624de68ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-danger btn-icon</value>
      <webElementGuid>91017bee-3ec1-4254-9868-9229df824bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>43dab0f3-be64-4dd4-95d7-3d8a7d26c2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#modalKonfirmasi</value>
      <webElementGuid>afdd1475-3698-454b-a1c8-db191e80319f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nip-pgw</name>
      <type>Main</type>
      <value>195803261986011001</value>
      <webElementGuid>3254584a-1e26-4777-93f5-c37602ab46f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>https://dev-payroll.its.ac.id/pegawai/drop-keaktifan/7C22FFC5-25F2-42C0-97CF-012A240BF3F0/5/2022</value>
      <webElementGuid>9e0a5475-ec8d-444a-aaa4-1eec8533289f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabelKeaktifan&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;td-its small&quot;]/button[@class=&quot;btn btn-danger btn-icon&quot;]</value>
      <webElementGuid>2a2dbf18-1b75-488e-9e21-43b59e81f541</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>1ab58a45-9b20-4e0d-a3f1-9d76a14eb749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabelKeaktifan']/tbody/tr/td[17]/button</value>
      <webElementGuid>60b350c0-6e86-4365-a667-45f4ef53a551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dosen'])[2]/following::button[1]</value>
      <webElementGuid>eac36b5e-4837-420a-8586-0f40b668be80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[1]/following::button[1]</value>
      <webElementGuid>39b96b8d-4842-4234-8e72-728b10eb9e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EA2EF009-80FD-42AB-A595-015934164064'])[1]/preceding::button[1]</value>
      <webElementGuid>17cfd1fd-4605-44f7-850d-5b5f4c8ba9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ir. Wahju Herijanto M.T.'])[1]/preceding::button[1]</value>
      <webElementGuid>3b0fc23f-10cf-4dcf-903e-7186d9646628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[17]/button</value>
      <webElementGuid>598cb67d-12a8-4305-8e82-ef7d2979a6b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>4156d94a-f6cb-4fd1-b940-ee10d545077a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
