<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Januari                             _2ee1cd</name>
   <tag></tag>
   <elementGuidId>99549446-c629-4853-9399-db03a45ba510</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='bulan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;bulan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>533b3a2a-dea8-4723-a525-e5b8162ddbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-sm</value>
      <webElementGuid>c6b679c0-5047-4f0c-8d9b-b499dae6f731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bulan</value>
      <webElementGuid>441727e6-77dd-4739-93d5-b6ac3a6fc59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            
                                                        Januari
                                                        Februari
                                                        Maret
                                                        April
                                                        Mei
                                                        Juni
                                                        Juli
                                                        Agustus
                                                        September
                                                        Oktober
                                                        November
                                                        Desember
                                                    </value>
      <webElementGuid>0d3f7341-c4ff-4aee-957c-b4e054a9c569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row row-xs&quot;]/div[@class=&quot;col-sm-12 col-md-12 mb-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2 mr-3&quot;]/select[@class=&quot;form-control-sm&quot;]</value>
      <webElementGuid>7d40ba33-3c10-4e19-aab6-0189aafb3e2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='bulan']</value>
      <webElementGuid>a866b724-d625-4876-9a0a-a10bffa799d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div/div/form/div/div/select</value>
      <webElementGuid>4fc1b917-205b-451a-bbad-4a61744c65fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Keaktifan Pegawai'])[2]/following::select[1]</value>
      <webElementGuid>2863cb30-be5d-4c8a-be84-772dcea741ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan'])[1]/preceding::select[3]</value>
      <webElementGuid>f910a34e-71b9-4a65-8bdc-49e68e41ab42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tarik Data'])[1]/preceding::select[3]</value>
      <webElementGuid>433dbf7e-7daf-4641-896d-334cf8a36dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0ae831dd-8fb7-4c9e-8010-62d48517e0c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'bulan' and (text() = '
                            
                                                        Januari
                                                        Februari
                                                        Maret
                                                        April
                                                        Mei
                                                        Juni
                                                        Juli
                                                        Agustus
                                                        September
                                                        Oktober
                                                        November
                                                        Desember
                                                    ' or . = '
                            
                                                        Januari
                                                        Februari
                                                        Maret
                                                        April
                                                        Mei
                                                        Juni
                                                        Juli
                                                        Agustus
                                                        September
                                                        Oktober
                                                        November
                                                        Desember
                                                    ')]</value>
      <webElementGuid>ea25b9b8-0329-49f3-9a74-7e74139b1ddd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
