<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih bulan                         _05c812</name>
   <tag></tag>
   <elementGuidId>daff3d65-6a3b-4689-ba9d-31a48b60fc95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='bulan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;bulan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5a27fc45-a325-4ee4-b32c-4f837483390b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ea28d745-945c-487a-b1a9-e8c02cdc03fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bulan</value>
      <webElementGuid>44aef317-9b08-4458-b075-b6b817913042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                    Pilih bulan
                                                                        Januari
                                                                        Februari
                                                                        Maret
                                                                        April
                                                                        Mei
                                                                        Juni
                                                                        Juli
                                                                        Agustus
                                                                        September
                                                                        Oktober
                                                                        November
                                                                        Desember
                                                                    </value>
      <webElementGuid>47312d46-fa6e-4aa4-8ad8-b70f3c2c45cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajuanSlip&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/form[1]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>3a665c61-b78e-4256-bb9e-11a12ba9dd62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='bulan']</value>
      <webElementGuid>7345dd3c-50ac-4ecc-a33c-4a945ee71d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ajuanSlip']/div/div/form/div[2]/div/div/div/select</value>
      <webElementGuid>ee3ca867-d59c-4ce9-a894-ea70c5d041fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Periode'])[1]/following::select[1]</value>
      <webElementGuid>06aa0405-44f0-4fc0-8231-3a4bed6070af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::select[1]</value>
      <webElementGuid>e9423499-080c-4d84-a594-5a1406dc35b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Slip'])[1]/preceding::select[2]</value>
      <webElementGuid>f4667814-92c8-4acf-89c6-98e93d413811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keperluan'])[2]/preceding::select[3]</value>
      <webElementGuid>74cd9353-4052-45e0-8cd5-4d1160091193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>361ca471-ab06-420f-bf8c-d16fe3ce3d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'bulan' and (text() = '
                                    Pilih bulan
                                                                        Januari
                                                                        Februari
                                                                        Maret
                                                                        April
                                                                        Mei
                                                                        Juni
                                                                        Juli
                                                                        Agustus
                                                                        September
                                                                        Oktober
                                                                        November
                                                                        Desember
                                                                    ' or . = '
                                    Pilih bulan
                                                                        Januari
                                                                        Februari
                                                                        Maret
                                                                        April
                                                                        Mei
                                                                        Juni
                                                                        Juli
                                                                        Agustus
                                                                        September
                                                                        Oktober
                                                                        November
                                                                        Desember
                                                                    ')]</value>
      <webElementGuid>b8bf5e6d-f929-41f2-bbea-32f5563be0a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
