<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Form</name>
   <tag></tag>
   <elementGuidId>46c8f107-78f1-4ed3-b89e-00a07c56df16</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='daftarAjuanSlip']/tbody/tr/td[8]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = 'https://dev-payroll.its.ac.id/take_home_pay/form-suket/B1138F65-4291-4EB7-8192-596EF68EC6AA/4/2022/00F53B15-E051-49EA-976B-10FDF13B6250' and (text() = 'Form' or . = 'Form')]</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98c7f203-9f67-4320-a5d0-d8be29180d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev-payroll.its.ac.id/take_home_pay/form-suket/B1138F65-4291-4EB7-8192-596EF68EC6AA/4/2022/00F53B15-E051-49EA-976B-10FDF13B6250</value>
      <webElementGuid>32f4f4eb-4293-414b-b541-8741fd833496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>c6b5dc39-eac7-45d4-9cbe-6a4bc650cc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Form</value>
      <webElementGuid>6e6174d8-e301-4e38-ab2f-5b5ffa7b394c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;daftarAjuanSlip&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;td-its&quot;]/a[1]</value>
      <webElementGuid>58abc2ef-8585-4df2-a153-5e84c5acef36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='daftarAjuanSlip']/tbody/tr/td[8]/a</value>
      <webElementGuid>981fe6c6-8f81-4ae9-9abf-e51725d0b6f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Form')]</value>
      <webElementGuid>226dbb23-1175-4a0e-92bc-9c546f35b923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PDF'])[1]/following::a[1]</value>
      <webElementGuid>f0134272-ea25-4475-b18c-0e732539c75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test'])[1]/following::a[2]</value>
      <webElementGuid>855afc33-72ca-4f95-8075-d57bdc212581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[1]/preceding::a[1]</value>
      <webElementGuid>b0b1c146-056e-47b3-aa2c-4750c8be8d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rizky Adi Putra'])[3]/preceding::a[1]</value>
      <webElementGuid>0ea06425-93ce-49ed-aa75-7920bb236282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Form']/parent::*</value>
      <webElementGuid>c9ed8d1f-ea0e-4318-bbb1-6b7de21351fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev-payroll.its.ac.id/take_home_pay/form-suket/B1138F65-4291-4EB7-8192-596EF68EC6AA/4/2022/00F53B15-E051-49EA-976B-10FDF13B6250')]</value>
      <webElementGuid>1ce111f5-8021-4393-b483-7d41b1bf8d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a</value>
      <webElementGuid>2989711d-6c98-42f8-93cf-efd40b5c3606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev-payroll.its.ac.id/take_home_pay/form-suket/B1138F65-4291-4EB7-8192-596EF68EC6AA/4/2022/00F53B15-E051-49EA-976B-10FDF13B6250' and (text() = 'Form' or . = 'Form')]</value>
      <webElementGuid>76920bcf-a880-4922-868c-b4a38c651c8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
