<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tunj_pembulatan</name>
   <tag></tag>
   <elementGuidId>4a00e53f-a15f-4a0f-879a-360007f7ecdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tunj_pembulatan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tunj_pembulatan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a75da8d4-fc2a-4e0c-9e67-6c55fd8f8596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef7019bb-e544-48a8-8dff-aa76f767437a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uang penghasilan</value>
      <webElementGuid>e0fb9134-6c71-467e-9627-44539282af08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tunj_pembulatan</value>
      <webElementGuid>d676ff44-8eb0-4de0-8ccb-d42b1f67d6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>80e22f61-5eb6-48b9-a043-768365881338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>rekalkulasi()</value>
      <webElementGuid>195bbf53-cbb2-4c49-a959-7b7e94ac5992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row row-xs&quot;]/div[@class=&quot;col-sm-12 col-lg-12&quot;]/form[1]/div[@class=&quot;card p-3&quot;]/div[@class=&quot;row mb-1&quot;]/div[@class=&quot;col-6&quot;]/input[@class=&quot;form-control uang penghasilan&quot;]</value>
      <webElementGuid>6bdc51f6-f3d6-4482-affd-e1623d9183f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tunj_pembulatan']</value>
      <webElementGuid>f1545e85-65f3-464a-91e6-c93713bad400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/div/div[13]/div[3]/input</value>
      <webElementGuid>6769bc73-cdb8-427f-8c08-62f751eacf6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div[3]/input</value>
      <webElementGuid>1015598b-f539-47e2-a1ff-9b698a240229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tunj_pembulatan']</value>
      <webElementGuid>030271c3-5e51-4a7a-ac30-8262e404387a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
