<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pot_bpjs</name>
   <tag></tag>
   <elementGuidId>b0610f29-57ff-46f7-afbe-2d17a34d145c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pot_bpjs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pot_bpjs&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c0e26be-e689-4bc2-92f4-3574c3e8cdc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c5ee22b1-f83a-4f4b-ac07-2fdd045290e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uang potongan</value>
      <webElementGuid>25f40d36-212b-4527-a57f-c68514e87377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pot_bpjs</value>
      <webElementGuid>9f14980f-4b1e-4dc0-b425-5db3aaa77885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>89b9e4f9-f34a-4d47-9971-1dc3591e1b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>rekalkulasi()</value>
      <webElementGuid>bcc67978-5688-4d37-98ee-311b6ebb8e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row row-xs&quot;]/div[@class=&quot;col-sm-12 col-lg-12&quot;]/form[1]/div[@class=&quot;card p-3&quot;]/div[@class=&quot;row mb-1&quot;]/div[@class=&quot;col-6&quot;]/input[@class=&quot;form-control uang potongan&quot;]</value>
      <webElementGuid>ac90c328-e350-4140-b080-b7e2cc3a9389</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pot_bpjs']</value>
      <webElementGuid>293b4735-fa6f-4596-85ad-72bc36349c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/div/div[20]/div[3]/input</value>
      <webElementGuid>236a6067-f4ab-4a7a-bfd8-62a5bf931009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div[3]/input</value>
      <webElementGuid>366a651b-95aa-447c-988c-740d2ad67876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pot_bpjs']</value>
      <webElementGuid>4d5e940d-752b-4b35-aaf4-fb80ef65020e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
