<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tampilkan_cek_uang_makan</name>
   <tag></tag>
   <elementGuidId>8fbc5f2c-9ca1-496b-84a8-02b6264b1b66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cek_uang_makan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cek_uang_makan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f29217f5-016e-49b8-88b3-6f2db3b31c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>f89cd673-016e-4906-ad70-40adc7a78d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>dee3dba4-0738-4362-9c0b-fb1690b97bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cek_uang_makan</value>
      <webElementGuid>7cdb74ad-840b-4976-aad8-d33f34fd12a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>cek('uang_makan')</value>
      <webElementGuid>77d1d19d-90f5-4d80-8661-94b566d0101d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row row-xs&quot;]/div[@class=&quot;col-sm-12 col-lg-12&quot;]/form[1]/div[@class=&quot;card p-3&quot;]/div[@class=&quot;row mb-1&quot;]/div[@class=&quot;col-3&quot;]/div[@class=&quot;form-check mb-2 mr-sm-2&quot;]/label[@class=&quot;form-check-label&quot;]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>33002e65-f5d2-4a3b-92a9-d519b634f302</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cek_uang_makan']</value>
      <webElementGuid>6502c9fc-608d-4cf6-93de-82bcd13a4446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/div/div[31]/div[4]/div/label/input</value>
      <webElementGuid>a80b880f-bfb6-4f38-ae6d-27b087293e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]/div[4]/div/label/input</value>
      <webElementGuid>9bf95a1c-173e-4044-84f3-332a28657996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'cek_uang_makan']</value>
      <webElementGuid>8656c54b-26a6-44f7-863f-bcffad4bdfd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
