<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__tunj_fungsional</name>
   <tag></tag>
   <elementGuidId>3f94ea2b-cf97-4418-9221-0ef1dda474da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tunj_fungsional']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tunj_fungsional&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f33161a-2b2a-4e85-9fd5-f474fad8dc57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1387585f-9cd0-400c-8853-e307a95a5545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uang penghasilan</value>
      <webElementGuid>dbd76647-2346-4d55-a175-f664a4bfa197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tunj_fungsional</value>
      <webElementGuid>ec168b70-3132-4444-86a7-43f481649598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>32e94742-3b8b-42dd-9a51-f7fa4c159ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>rekalkulasi()</value>
      <webElementGuid>c9e39d37-e898-49c4-881f-e3e00b0f2b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row row-xs&quot;]/div[@class=&quot;col-sm-12 col-lg-12&quot;]/form[1]/div[@class=&quot;card p-3&quot;]/div[@class=&quot;row mb-1&quot;]/div[@class=&quot;col-6&quot;]/input[@class=&quot;form-control uang penghasilan&quot;]</value>
      <webElementGuid>e01a941c-c2ba-4c52-a895-79bb498daa84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tunj_fungsional']</value>
      <webElementGuid>e6f9fb0b-fa7a-4557-98fc-1b4cb502144d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/div/div[5]/div[3]/input</value>
      <webElementGuid>36a37a6f-1644-4709-a46f-0fd789f58ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/input</value>
      <webElementGuid>ec211c99-4953-4716-8900-4245bec368b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'tunj_fungsional']</value>
      <webElementGuid>041a1e9c-ccc4-425d-b9e1-7d53c3985f6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
