<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__total_penghasilan</name>
   <tag></tag>
   <elementGuidId>870e0850-a36d-45aa-837d-e0ef8f5c7b1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='total_penghasilan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;total_penghasilan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c88e3678-5803-4da8-ac02-fc7e20f649f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4cd2d0f5-3dd1-4018-9c48-67d37b5887f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uang</value>
      <webElementGuid>3ebb0609-c46f-4ffa-9fac-509ee38ffe11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>total_penghasilan</value>
      <webElementGuid>47f88c7f-e412-4ea0-9efc-faf216cf1d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6eb98cd2-3054-4dd0-a343-68c742a256bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row row-xs&quot;]/div[@class=&quot;col-sm-12 col-lg-12&quot;]/form[1]/div[@class=&quot;card p-3&quot;]/div[@class=&quot;row mb-1 mt-3&quot;]/div[@class=&quot;col-6&quot;]/input[@class=&quot;form-control uang&quot;]</value>
      <webElementGuid>73d0e47c-d4f8-45b7-8db7-4b6c1b61ebc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='total_penghasilan']</value>
      <webElementGuid>2b0b9d56-a998-4f65-bf9c-07163d5f3dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/div/div[33]/div[3]/input</value>
      <webElementGuid>d24c29aa-79d7-40f6-8b00-e7bf0c9ff55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[33]/div[3]/input</value>
      <webElementGuid>d0ca9d01-7877-48b7-9d0f-89077ca43266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'total_penghasilan']</value>
      <webElementGuid>59708f1a-75bc-4c2e-97f4-8f1b70a92e2b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
