<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tampilkan_cek_pot_bpjs</name>
   <tag></tag>
   <elementGuidId>303bf26e-dc87-4af5-b90f-13a374e09fcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cek_pot_bpjs']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cek_pot_bpjs&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>072215f4-2722-4132-bfbd-a71c2c0bacf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>26fb6e01-03de-4b7b-b4e3-e2bdf30f5c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>345bd2c0-432e-43e9-8a97-559b50c0b442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cek_pot_bpjs</value>
      <webElementGuid>b4b58445-a8ad-4350-90a3-648493383e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>cek('pot_bpjs')</value>
      <webElementGuid>87167757-1f43-4944-8624-129a5765eba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row row-xs&quot;]/div[@class=&quot;col-sm-12 col-lg-12&quot;]/form[1]/div[@class=&quot;card p-3&quot;]/div[@class=&quot;row mb-1&quot;]/div[@class=&quot;col-3&quot;]/div[@class=&quot;form-check mb-2 mr-sm-2&quot;]/label[@class=&quot;form-check-label&quot;]/input[@class=&quot;form-check-input&quot;]</value>
      <webElementGuid>15015019-3345-4db6-9bf3-f9145ec3e9b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cek_pot_bpjs']</value>
      <webElementGuid>d5597a15-6c70-4138-b44b-5ed01b7068a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/form/div/div[20]/div[4]/div/label/input</value>
      <webElementGuid>bdeef9d8-3f14-4dff-b374-34876ae97f9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div[4]/div/label/input</value>
      <webElementGuid>7a44c70b-981c-4a86-ab70-94378694149b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'cek_pot_bpjs']</value>
      <webElementGuid>01f071c4-3508-47ed-aeb0-13f8f0f0aba6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
