<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_1998202241014</name>
   <tag></tag>
   <elementGuidId>270fcd36-5ea6-449b-8140-c748517a0613</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tabelPegawai']/tbody/tr/td[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.td-its.small > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e1d25c02-813a-4c17-b8df-2738e0a0894f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://dev-payroll.its.ac.id/pegawai/detail-pegawai/B1138F65-4291-4EB7-8192-596EF68EC6AA</value>
      <webElementGuid>a4f8b6c8-0f85-4e77-b683-7b7fdf84713c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1998202241014</value>
      <webElementGuid>96b829ed-78ce-4511-9e96-3d49ae61c743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabelPegawai&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;td-its small&quot;]/a[1]</value>
      <webElementGuid>7842ae2a-a03a-48fb-9e70-dc0714562c2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabelPegawai']/tbody/tr/td[2]/a</value>
      <webElementGuid>38591c11-301d-4e89-ba05-4e1cc06de175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'1998202241014')]</value>
      <webElementGuid>209fec81-ec7e-416b-8c9c-9bd1c91330e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B1138F65-4291-4EB7-8192-596EF68EC6AA'])[1]/following::a[1]</value>
      <webElementGuid>15867851-1a4e-491c-ad77-3b1ea27e9070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NPWP'])[2]/following::a[1]</value>
      <webElementGuid>4ceddd7d-ca16-4132-a317-42d7ba7004cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rizky Adi Putra S.Kom'])[1]/preceding::a[1]</value>
      <webElementGuid>d1fc5c79-e7f0-41aa-8a9e-6591c758ecb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktif'])[1]/preceding::a[1]</value>
      <webElementGuid>e7aaea2c-6974-4c1e-83c6-d0ac8844e51b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1998202241014']/parent::*</value>
      <webElementGuid>7da9f514-3d81-4699-b1ba-5c1276a14854</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://dev-payroll.its.ac.id/pegawai/detail-pegawai/B1138F65-4291-4EB7-8192-596EF68EC6AA')]</value>
      <webElementGuid>cd993aa2-7f97-4ec4-bc8e-0f16839b1f67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>9f04ad8b-9830-4955-a7a4-b7e98341bfab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://dev-payroll.its.ac.id/pegawai/detail-pegawai/B1138F65-4291-4EB7-8192-596EF68EC6AA' and (text() = '1998202241014' or . = '1998202241014')]</value>
      <webElementGuid>4b1e1df5-c543-4785-a13c-c38e0f4589de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
