<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Menampilkan 1 sampai 25 dari 3,148 entri</name>
   <tag></tag>
   <elementGuidId>0e47aeb3-3906-45f2-b3a0-4577866db9cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabelPegawai_info']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tabelPegawai_info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9dd993d8-5fd9-43d9-8325-7a68650c3f2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_info</value>
      <webElementGuid>99b6089f-986f-4240-a27f-ee57d9ce190e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabelPegawai_info</value>
      <webElementGuid>4414beb7-4247-422c-99e9-b45fb644b3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>95a0e538-1f8f-4aa8-83bd-61ddf165fd12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>9d815671-42e2-4e92-bd9d-063beed0d154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menampilkan 1 sampai 25 dari 3,148 entri</value>
      <webElementGuid>c9da1be8-8362-4272-af88-0096464bc353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabelPegawai_info&quot;)</value>
      <webElementGuid>436c2a14-bc8a-4cc3-b406-101b77c39e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='tabelPegawai_info']</value>
      <webElementGuid>fa05029b-445e-430a-a58f-546a2546fefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabelPegawai_wrapper']/div[3]</value>
      <webElementGuid>a97d5e34-2746-4ad2-988f-0e51715b2477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BNI'])[16]/following::div[1]</value>
      <webElementGuid>b035f2ba-c2d9-4231-9dce-7298b4aa9c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ibu Dini Ermavitalini'])[1]/following::div[1]</value>
      <webElementGuid>4f829e31-de99-4f28-9006-85c166575518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::div[1]</value>
      <webElementGuid>1183fb58-6575-4f57-a06b-7512bdd6299e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='…'])[1]/preceding::div[1]</value>
      <webElementGuid>fa06ec06-d28d-4114-9077-5c127d35d4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Menampilkan 1 sampai 25 dari 3,148 entri']/parent::*</value>
      <webElementGuid>9bbfaba9-5c53-4f88-919f-7359325f1256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]</value>
      <webElementGuid>4338889b-a0fb-4f0c-a932-40fc4b97d48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'tabelPegawai_info' and (text() = 'Menampilkan 1 sampai 25 dari 3,148 entri' or . = 'Menampilkan 1 sampai 25 dari 3,148 entri')]</value>
      <webElementGuid>28f2922e-7e4d-4e5f-98c6-51a0a3a0c03c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
