<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_102550Semua</name>
   <tag></tag>
   <elementGuidId>d2be8829-5a74-48fe-89cc-0a24dafe11c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;tabelPegawai_length&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'tabelPegawai_length' and (text() = '102550Semua' or . = '102550Semua')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>384cee07-5705-4a7b-989f-bb7c48da601f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tabelPegawai_length</value>
      <webElementGuid>29c68fdf-706a-4cec-84de-d0ae3512119a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>tabelPegawai</value>
      <webElementGuid>ce3d34c1-ebdb-470c-8769-20a3e01d0a38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>102550Semua</value>
      <webElementGuid>b8bcd696-73fd-49e7-a1f4-e185a1ca6ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabelPegawai_length&quot;)/label[1]/select[1]</value>
      <webElementGuid>1a8b3733-f87f-4644-bb12-4306763e9dbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='tabelPegawai_length']</value>
      <webElementGuid>3ee81341-f6a8-4bfd-b900-eff7b62e9ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabelPegawai_length']/label/select</value>
      <webElementGuid>94fd3174-c6bb-4e93-a5b7-b5796734cdcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::select[1]</value>
      <webElementGuid>3866058e-2096-460d-bdf5-d097792a5bc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIP'])[1]/preceding::select[1]</value>
      <webElementGuid>b7dbfe19-bc36-4bc8-9d50-a5949d01d605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ec319a78-d485-4632-8529-ff28b3407d5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'tabelPegawai_length' and (text() = '102550Semua' or . = '102550Semua')]</value>
      <webElementGuid>6602c3bc-f140-4ce9-afe8-74ab2f762d7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
