<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_102550100</name>
   <tag></tag>
   <elementGuidId>55eefd22-d699-412d-afaf-7f2457e23b81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='table-perencanaan-pajak_length']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;table-perencanaan-pajak_length&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>715ce6b2-ab86-4b01-952b-81d1bb02c6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>table-perencanaan-pajak_length</value>
      <webElementGuid>7656d1d5-ea6c-4c25-8e03-eac9d55fc8d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>table-perencanaan-pajak</value>
      <webElementGuid>2737562d-e81f-4882-acea-30183a5a7df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>102550100</value>
      <webElementGuid>76e1db04-ce19-42a4-aade-3cdfe5fe78df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-perencanaan-pajak_length&quot;)/label[1]/select[1]</value>
      <webElementGuid>d344dc89-20fa-4e1e-92a4-84dcd2b6da56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='table-perencanaan-pajak_length']</value>
      <webElementGuid>e16c0044-aa5f-41af-b35b-82f1d39dd5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-perencanaan-pajak_length']/label/select</value>
      <webElementGuid>9dc19460-cdf1-4c2c-8d78-fc5c863b6cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hitung Ulang'])[1]/following::select[1]</value>
      <webElementGuid>472e50a8-4fb6-4551-8f22-fb3076a2f7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari:'])[1]/preceding::select[1]</value>
      <webElementGuid>c06619b7-1ff7-4fee-b26e-7ce6e0942be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/preceding::select[1]</value>
      <webElementGuid>4db3fc6c-da7d-4ab1-8e76-4e62cbcfd216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/select</value>
      <webElementGuid>4b552c2d-7ef6-47e9-b59b-feaa4b0ff016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'table-perencanaan-pajak_length' and (text() = '102550100' or . = '102550100')]</value>
      <webElementGuid>b09f70d3-398a-4c44-8360-f75672089f49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
