<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Solekan</name>
   <tag></tag>
   <elementGuidId>724b510f-14e7-491f-a480-14c86693c912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table-perencanaan-pajak']/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>117663fc-8ce6-4c91-afc3-ee8681a172ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>td-its</value>
      <webElementGuid>ac674b85-3807-4172-b66b-e582f0eb1421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solekan</value>
      <webElementGuid>daba6c71-c0bd-4061-a0c7-47ed919d8e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-perencanaan-pajak&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;td-its&quot;]</value>
      <webElementGuid>c15845a5-0a93-4209-968b-0e729f9e1f75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-perencanaan-pajak']/tbody/tr/td[3]</value>
      <webElementGuid>43abe538-ec74-401c-8587-6de1fd6950eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IKITS 2'])[1]/following::td[3]</value>
      <webElementGuid>b7eed9cc-2aec-4638-8b55-a016ddd927ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IKITS 1'])[1]/following::td[3]</value>
      <webElementGuid>88e6be3d-4010-4fe7-b61a-f6285435edb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan 1 sampai 1 dari 1 entri (disaring dari 3,149 entri keseluruhan)'])[1]/preceding::td[7]</value>
      <webElementGuid>42301682-e0b5-44a5-9f7a-002b92d17ca0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::td[7]</value>
      <webElementGuid>a3c29b35-e8fd-4095-ab23-f8913b789634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solekan']/parent::*</value>
      <webElementGuid>14c5e81c-cc87-4303-a990-31d6defc568f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>1da02b4b-e7b4-4ea4-948d-f46532cba6bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Solekan' or . = 'Solekan')]</value>
      <webElementGuid>c546973d-38c8-4720-b413-6d7c2a8b29c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
