<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Slip Gaji Pegawai_rounded-circle</name>
   <tag></tag>
   <elementGuidId>254d6fc1-f056-438e-ac24-19ee187fc0d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://dev-payroll.its.ac.id/assets/img/avatar15.jpg')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3c4dd74f-1f3c-4117-8bf2-55ba444caa45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev-payroll.its.ac.id/assets/img/avatar15.jpg</value>
      <webElementGuid>9ae6b6bb-84d1-42e2-b9ca-6e1b3940c10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src='https://dev-payroll.its.ac.id/assets/img/avatar15.jpg'</value>
      <webElementGuid>ee8a4e45-21ec-47dd-b673-951729d01bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle</value>
      <webElementGuid>bcba2a7d-1917-4961-9528-3e829da1127c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;content ht-100v pd-0&quot;]/div[@class=&quot;content-header align-items-center justify-content-start pos-fixed wd-100p z-index-10&quot;]/nav[@class=&quot;nav r-25 pos-fixed z-index-10&quot;]/div[@class=&quot;dropdown dropdown-profile&quot;]/a[@class=&quot;dropdown-link&quot;]/div[@class=&quot;avatar avatar-sm&quot;]/img[@class=&quot;rounded-circle&quot;]</value>
      <webElementGuid>fd492e4f-fca5-4e8a-9875-44abcf7e659b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev-payroll.its.ac.id/assets/img/avatar15.jpg')]</value>
      <webElementGuid>6e886450-c52f-4af5-8a4a-2fcdefd193a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>1fd54591-97e2-4351-bc9f-8cbc3bf57068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev-payroll.its.ac.id/assets/img/avatar15.jpg']</value>
      <webElementGuid>537a5412-14fb-4a5c-ab1c-3b58b37488d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
