<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_102550100</name>
   <tag></tag>
   <elementGuidId>27b81944-6009-45cb-9407-f53b20ca2c99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='table-realisasi-tpb_length']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;table-realisasi-tpb_length&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>596687d1-173a-4b3a-86f4-ef6c1d101d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>table-realisasi-tpb_length</value>
      <webElementGuid>094b174a-5d2e-4302-8a1d-5f86529dedc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>table-realisasi-tpb</value>
      <webElementGuid>9e88d89f-34e6-4432-b19e-c041a2755808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>102550100</value>
      <webElementGuid>b1ed750e-6081-4f48-a1fa-3b68ebe8c491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-realisasi-tpb_length&quot;)/label[1]/select[1]</value>
      <webElementGuid>98da9007-67b0-4a3f-a71e-fd06ee331ac8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='table-realisasi-tpb_length']</value>
      <webElementGuid>8d207437-2cb2-4755-9f99-42aa897273e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='table-realisasi-tpb_length']/label/select</value>
      <webElementGuid>13a8be3f-8839-42ce-8720-d584378129bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cari:'])[1]/preceding::select[1]</value>
      <webElementGuid>e52b65ad-6bdd-44b6-bc79-173ed7cf1675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/preceding::select[1]</value>
      <webElementGuid>2ce2a24e-e15c-4abc-b975-03c236f676e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>bfa4eb65-a745-49a2-8734-af24112e4bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'table-realisasi-tpb_length' and (text() = '102550100' or . = '102550100')]</value>
      <webElementGuid>bd5d84fb-b735-4f2c-8d8b-fef8c8a4a900</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
