<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Solekan</name>
   <tag></tag>
   <elementGuidId>9634aca9-9546-42b6-a9d7-024b33a23254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table-realisasi-tpb']/tbody/tr/td[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>75a965c2-4b5b-49c9-83de-494a3262909c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>td-its</value>
      <webElementGuid>056ce4e3-a242-4b8a-8958-dee83d1a8971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Solekan</value>
      <webElementGuid>7cec3fc2-4840-43cf-af9c-1587ed074f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table-realisasi-tpb&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[@class=&quot;td-its&quot;]</value>
      <webElementGuid>e95b2334-573b-4d6a-aaae-d7f1341b8490</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table-realisasi-tpb']/tbody/tr/td[3]</value>
      <webElementGuid>8905752d-ee6a-44fe-a7c7-2f03f25542cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IKITS 2'])[1]/following::td[3]</value>
      <webElementGuid>aacb2e73-1db4-4ea1-9d5f-22462fb79acf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IKITS 1'])[1]/following::td[3]</value>
      <webElementGuid>cf4a9996-d722-4d88-a8bb-90c904a2815d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menampilkan 1 sampai 1 dari 1 entri (disaring dari 3,149 entri keseluruhan)'])[1]/preceding::td[9]</value>
      <webElementGuid>20b47648-cf29-4292-a971-1503909b2ac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sebelumnya'])[1]/preceding::td[9]</value>
      <webElementGuid>4fd7ef0b-61e4-47a3-ad04-6924815db86c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Solekan']/parent::*</value>
      <webElementGuid>61f6d282-ff59-4a4c-9cd9-af5c6767b3a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]</value>
      <webElementGuid>a0616e9a-877e-47e5-ad8a-bef20d9ca502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Solekan' or . = 'Solekan')]</value>
      <webElementGuid>63a36f3b-7c08-49c2-9867-225455656efd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
