<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Pilih bulan                         _836dbc</name>
   <tag></tag>
   <elementGuidId>a6963136-8cc7-466a-9b38-ed740ef96796</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='bulan']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;bulan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bc59aa19-d480-4f36-b68d-af1f9b2e0bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>95a6efcc-000f-4b69-960f-e5bee4ce7b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bulan</value>
      <webElementGuid>3268aabb-1e6b-44fd-a5e0-88a560fe93c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Pilih bulan
                                                        Januari
                                                        Februari
                                                        Maret
                                                        April
                                                        Mei
                                                        Juni
                                                        Juli
                                                        Agustus
                                                        September
                                                        Oktober
                                                        November
                                                        Desember
                                                    </value>
      <webElementGuid>7a0c905e-94a5-415e-8bc6-3c3fd5149865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;row row-xs&quot;]/div[@class=&quot;col-sm-12 col-md-12 mb-4&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 mb-2&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>3b29fd10-7d06-4506-a2ec-4645cc3ecdf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='bulan']</value>
      <webElementGuid>e95e6ee5-70d8-4e7a-8de4-3c5543b68276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div/div/form/div/div[2]/select</value>
      <webElementGuid>74231526-f20d-4754-94b1-cede7ffb18ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rilis Final TPB'])[2]/following::select[2]</value>
      <webElementGuid>460f20e5-c87a-45be-a945-d5846633f2d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tampilkan'])[1]/preceding::select[4]</value>
      <webElementGuid>db99f083-6f41-4b92-a226-c9a189fdd97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unduh'])[1]/preceding::select[4]</value>
      <webElementGuid>4e0d660d-8b2d-4e76-a383-0330330c0572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>7feff190-a55e-4ad8-a355-aa438adee104</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'bulan' and (text() = '
                            Pilih bulan
                                                        Januari
                                                        Februari
                                                        Maret
                                                        April
                                                        Mei
                                                        Juni
                                                        Juli
                                                        Agustus
                                                        September
                                                        Oktober
                                                        November
                                                        Desember
                                                    ' or . = '
                            Pilih bulan
                                                        Januari
                                                        Februari
                                                        Maret
                                                        April
                                                        Mei
                                                        Juni
                                                        Juli
                                                        Agustus
                                                        September
                                                        Oktober
                                                        November
                                                        Desember
                                                    ')]</value>
      <webElementGuid>495b811e-904a-4403-9148-c8e6b2b11115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
