<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rilis Final TPB</name>
   <tag></tag>
   <elementGuidId>651f8dbc-7e5c-4e47-a47d-4191f3618828</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='sideMenu']/li[22]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21a54c17-c5d0-4244-a73e-1e7a5f9b3396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rilis Final TPB</value>
      <webElementGuid>ae3f6248-b48d-48e7-b1b5-bd88fcc21a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sideMenu&quot;)/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>e27ec8c1-e8d2-4b0b-b77f-3ff3cd963dd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sideMenu']/li[22]/a/span</value>
      <webElementGuid>344f77bd-9e03-47a3-90dc-40d535344846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rilis Bruto TPB'])[1]/following::span[1]</value>
      <webElementGuid>80e18b15-4340-4bec-92f2-66abf07491ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TPB'])[1]/following::span[2]</value>
      <webElementGuid>19c8dc5c-1f32-4238-aa68-ba1665fe61a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remunerasi'])[1]/preceding::span[1]</value>
      <webElementGuid>0df65763-8f16-45f0-bab3-72961331dae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rilis Bruto Remunerasi'])[1]/preceding::span[1]</value>
      <webElementGuid>97f7e57f-8299-41ce-ba2e-3c5d85e78dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rilis Final TPB']/parent::*</value>
      <webElementGuid>6c7e98f8-9889-4ec0-8d9d-4dc9e0d008f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[22]/a/span</value>
      <webElementGuid>50d27ad3-bd58-472f-82de-f6477d3e92b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rilis Final TPB' or . = 'Rilis Final TPB')]</value>
      <webElementGuid>0b1147e4-217e-4bec-864a-19fc4f5238ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
