<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rincian Pot. Pendapatan</name>
   <tag></tag>
   <elementGuidId>e2714313-4ec1-4da5-b12f-a5b9e6b01b50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='sideMenu']/li[11]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9c421459-45a7-4e73-bb1f-83d8434f1ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rincian Pot. Pendapatan</value>
      <webElementGuid>ef75a14e-cc3e-41ca-bd05-06a9388ed469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sideMenu&quot;)/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link&quot;]/span[1]</value>
      <webElementGuid>00f8a9f2-1df8-485c-b8a4-669a02ed2f04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='sideMenu']/li[11]/a/span</value>
      <webElementGuid>60cc36fd-d1b7-48e4-8426-13e88993d2de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rincian Pendapatan'])[1]/following::span[1]</value>
      <webElementGuid>7ca7655e-cca5-4bf1-b7ee-d1e97a28ff47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Take Home Pay'])[1]/following::span[2]</value>
      <webElementGuid>2b6e2001-d316-4305-86a5-28721170d98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Potong Pajak'])[1]/preceding::span[1]</value>
      <webElementGuid>dbc706e8-6e01-4694-a010-6a6a6538cca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SPT Tahunan'])[1]/preceding::span[2]</value>
      <webElementGuid>fb0d8c3d-8f45-42ee-8f4c-d1b3ee5cc73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rincian Pot. Pendapatan']/parent::*</value>
      <webElementGuid>b44882ce-e79e-4066-b070-388e6a57f178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[11]/a/span</value>
      <webElementGuid>ed4ecf9a-d4e8-4474-9c78-01ad758d0901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rincian Pot. Pendapatan' or . = 'Rincian Pot. Pendapatan')]</value>
      <webElementGuid>96971c64-1d41-493f-b8bf-f7fa21a7b7d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
