<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Change</name>
   <tag></tag>
   <elementGuidId>066b447b-fdfb-4beb-8b2b-b171fab84ba9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-its.float-right.tx-montserrat.tx-semibold</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>aeb66bee-745e-4946-9136-3c82a20b5abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>452b3ba4-4abf-4624-935d-896c96754101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-its float-right tx-montserrat tx-semibold</value>
      <webElementGuid>42b8e4a1-3e05-4d3c-8d18-b82cda027925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Change</value>
      <webElementGuid>7c9e21ec-0c3c-4ed5-af81-58704f467595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chgRoleUser&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content bg-white&quot;]/div[@class=&quot;modal-body&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn btn-its float-right tx-montserrat tx-semibold&quot;]</value>
      <webElementGuid>4d5c2d8b-73c7-4af4-b5db-547570b0b8e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>cebecb60-0e68-4a83-9169-67a8571be98c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chgRoleUser']/div/div/div/form/div[2]/button</value>
      <webElementGuid>ac8efab7-352f-4384-a82a-c8d6a1cc1dc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pegawai'])[4]/following::button[1]</value>
      <webElementGuid>95ff5017-e7dc-4833-a6f1-c1d069827b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roles'])[1]/following::button[1]</value>
      <webElementGuid>68eaa7f5-f78e-43ed-a66d-85dafead64fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>fb25223c-0087-4f4f-a36b-f4dc68c10b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Change']/parent::*</value>
      <webElementGuid>26eb1a78-90a9-4b32-9b86-9c951871d3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>0c32ba2d-e07c-4116-9f1c-1dda48376f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Change' or . = 'Change')]</value>
      <webElementGuid>b3f8130d-3afa-4b9d-bd88-4be67205a2a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
