<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Slip Gaji Pegawai_rounded-circle</name>
   <tag></tag>
   <elementGuidId>dee6b369-7fc2-4322-b7ae-85c7da04b558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rounded-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://dev-payroll.its.ac.id/assets/img/avatar15.jpg')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8a683018-539d-4814-ab03-2002262f29a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dev-payroll.its.ac.id/assets/img/avatar15.jpg</value>
      <webElementGuid>ad2ced7e-5e13-4cd8-bf15-72d6ffcc577a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.src='https://dev-payroll.its.ac.id/assets/img/avatar15.jpg'</value>
      <webElementGuid>0003fd2d-194f-47f2-add9-5e3938bf992d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rounded-circle</value>
      <webElementGuid>70491f26-a18c-44f8-95a6-ecbab7ec15e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;content ht-100v pd-0&quot;]/div[@class=&quot;content-header align-items-center justify-content-start pos-fixed wd-100p z-index-10&quot;]/nav[@class=&quot;nav r-25 pos-fixed z-index-10&quot;]/div[@class=&quot;dropdown dropdown-profile&quot;]/a[@class=&quot;dropdown-link&quot;]/div[@class=&quot;avatar avatar-sm&quot;]/img[@class=&quot;rounded-circle&quot;]</value>
      <webElementGuid>a8427821-cdd6-4df9-8114-fe4292bbaab1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://dev-payroll.its.ac.id/assets/img/avatar15.jpg')]</value>
      <webElementGuid>13e21380-a74d-4134-a325-3046c5806067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>b896ffc8-c826-4371-b20d-54516d91378f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://dev-payroll.its.ac.id/assets/img/avatar15.jpg']</value>
      <webElementGuid>152fa291-f829-4939-ba96-6bfcbdcf9463</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
